#:schema node_modules/wrangler/config-schema.json
main = ".open-next/worker.js"
name = "fifa26-predictions"
account_id = "a76a117ad4225d384a4a2dc22ebece83"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "fifa26-predictions"

[images]
binding = "IMAGES"

[[d1_databases]]
binding = "DB"
database_name = "fifa26-predictions-db"
database_id = "a1de6e9f-732f-43e3-8882-7502dace5e12"

[vars]
NODE_ENV = "production"

[observability]
enabled = false

[triggers]
crons = [
  "*/5 12-23 * 6-7 *",
  "*/30 0-11 * 6-7 *",
  "0 * * 1-5,8-12 *"
]
